### ISSUE TITLE
Availability to reset password for other apps

### ISSUE THREAD

**Issue by swarlyru** [lithnet/resourcemanagement-ui-assistedpasswordreset#10]
Hello, have a question if it is possible to modify your utility for resetting password in another application that is connected to mim and has password management configured?

**Comment by ryannewington** [comment]
Do you mean without changing their AD password at the same time?

At the moment, it changes their AD password and any connected systems enabled for password management.

**Comment by swarlyru** [comment]
Just on the particular connector, our customer wanted to assisted change password only on sap systems and not change adds passwords....
I know is a kind of weird but that's what they want, I am thinking to implement your approach and use password change method connecting using wmi on sync engine sap web service connector.
You think is possible?
Thx.
--
Sent from Mail.ru app for Android Saturday, 07 December 2019, 08:41AM +03:00 from Ryan Newington  notifications@github.com :

**Comment by ryannewington** [comment]
The SetPassword method seems to be only available on certain connector types

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ms697760%28v%3dvs.100%29

I'm not sure how accurate that documentation is. I'd test using a WMI command line tool to see if it accepts the password change. If so you could fork the code if you are confortable doing that. If you don't have in house dev skills, or if you're looking for a custom solution for your customer, we can quote on this. Send an email to support@lithnet.io with the details of what would be required.

**Comment by swarlyru** [comment]
Thx, I will try to do it by myself, will let you know if any.

--
Sent from Mail.ru app for Android Monday, 09 December 2019, 03:44AM +03:00 from Ryan Newington  notifications@github.com :
