### ISSUE TITLE
Acces denied: Password Reset

### ISSUE THREAD

**Issue by alexvara** [lithnet/resourcemanagement-ui-assistedpasswordreset#4]
My Trouble is  when i try password reset to an user, send a red words, say.

Acces Denied.

what happened, something i did wrong?

**Comment by ryannewington** [comment]
Hi @alexvara,

That message indicates that you don't have permissions in Active Directory to reset passwords. Are you able to reset the user's password using the standard Active Directory Users and Computers tool?

Ryan

**Comment by alexvara** [comment]
Hi Rayan,

Yeah, i Guess yeah, but what kind permission need the account?

Because the account sync with Active Directory have enterprise admin permission.

Thanks.

Regards!



El 15 mar. 2017 5:16 p. m., Ryan Newington <notifications@github.com> escribió:

Hi @alexvara<https://github.com/alexvara>,

That message indicates that you don't have permissions in Active Directory to reset passwords. Are you able to reset the user's password using the standard Active Directory Users and Computers tool?

Ryan

**Comment by alexvara** [comment]
Ryan, I´ve check the permissions and is Ok.

Something more to do, I followed the instructions!

Regards,

**Comment by ryannewington** [comment]
@alexvara,

If you have confirmed that you can reset passwords directly in AD, and are still having problems, download and run dbgview (https://technet.microsoft.com/en-us/sysinternals/debugview.aspx) on the MIM portal server.

Ensure that the application is running with elevated administrative rights, and select "Capture Win32" and "Capture Global Win32"

![image](https://cloud.githubusercontent.com/assets/17229877/24064367/22190f22-0bb8-11e7-86ca-8769b8ecdccf.png)

Once it is running, attempt a password reset operation. Save the resulting dbgview log file and attach it to this ticket.

Ryan

**Comment by alexvara** [comment]
Ryan,

Jesus Olguin noticed that could add a line with Elevated Privileges, then he added SPSecurity.RunWithElevatedPrivileges(() =>

And the solution worked.

Thanks Rayan.

**Comment by alexvara** [comment]
Ryan,

Jesus Olguin noticed that could add a line with Elevated Privileges, then he added SPSecurity.RunWithElevatedPrivileges(() =>

And the solution worked.

Thanks Rayan.



AVJ

**Comment by ryannewington** [comment]
@alexvara can you confirm where that line was added to make it work? If needed, I can update the solution and fix this for everyone.
