### ISSUE TITLE
Module does not load on SharePoint 2010

### ISSUE THREAD

**Issue by jlclaude** [lithnet/resourcemanagement-ui-assistedpasswordreset#5]
Could not load file or assembly 'AjaxControlToolkit' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

sharepoint 2010 is the version I am using

**Comment by ryannewington** [comment]
Hi @jlclaude,

It seems SharePoint 2010 only supports .NET 3.5. This tool (and the library it uses requires .NET 4).

I'm afraid it looks like SharePoint 2013 is the minimum supported version to be able to use this product.

Sorry about that. It wasn't something I realised until now.

Ryan
