### ISSUE TITLE
Error Message: The user was not found

### ISSUE THREAD

**Issue by mwassell** [lithnet/resourcemanagement-ui-assistedpasswordreset#6]
Hi Ryan, first of all, thank you for your hard work and thanks for providing this SP to the community.

I was troubleshooting a "The user was not found error" with this SP module and I thought that I would share the (admittedly simple) fix. The fix involved creating an MPR in the FIM Portal to grant Read access to the Resource SID attribute of the User object type.

I didn't notice this step included in the project Wiki page, and I expect that this may creep up on someone else down the road...

Below is the debug output:

`00000026	75.41978455	[25700] Loaded page as DOMAIN\NormalUser using Negotiate authentication 	
00000027	75.65811920	[25700] Got resource urn:uuid:6eab3a88-fafe-404f-846e-be59099dfd5a from resource management service 	
00000028	75.65817261	[25700] Got localized display name for DisplayName-Person-en-CA from cache 	
00000029	75.65827179	[25700] Row 0 added 	
00000030	75.65830994	[25700] Got localized display name for AccountName-Person-en-CA from cache 	
00000031	75.65835571	[25700] Row 1 added 	
00000032	75.65840149	[25700] Got localized display name for Domain-Person-en-CA from cache 	
00000033	75.65844727	[25700] Row 2 added 	
00000034	75.65848541	[25700] No SID found on the user object 	
00000035	75.65851593	[25700] Setting error message: The user was not found 
`
	
`00000037	253.89151001	[25700] Loaded page as DOMAIN\NormalUser using Negotiate authentication 	
00000038	254.13105774	[25700] Got resource urn:uuid:6eab3a88-fafe-404f-846e-be59099dfd5a from resource management service 	
00000039	254.13110352	[25700] Got localized display name for DisplayName-Person-en-CA from cache 	
00000040	254.13116455	[25700] Row 0 added 	
00000041	254.13119507	[25700] Got localized display name for AccountName-Person-en-CA from cache 	
00000042	254.13125610	[25700] Row 1 added 	
00000043	254.13128662	[25700] Got localized display name for Domain-Person-en-CA from cache 	
00000044	254.13133240	[25700] Row 2 added 	
00000045	254.13137817	[25700] Set target set to S-1-5-21-[sid]`

**Comment by ryannewington** [comment]
Added additional step to the installation guide
