### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Bob-Bradley** [lithnet/resourcemanagement-ui-assistedpasswordreset#9]
Hi Ryan
I notice there is no LICENSE document on this repository.  Are you able to add a license document or is there a reason why you haven't to date?
Thanks
Bob
P.S. We still see a recurring need for this sort of solution and intend to ultimately contribute to this and other repos in your excellent collection.

**Comment by zaeja** [comment]
Hi Bob,
Thanks for pointing this out! I've added the MIT license after discussing it with Ryan, and we look forward to your future contributions!
Cheers,
Brett.
